name: Release

on:
  push:
    branches:
    - main

jobs:
  build:
  runs-on: ubuntu-latest
  permissions:
    contents: write
  steps:
  - uses: https://github.com/actions/checkout@v2
  - uses: https://github.com/actions/setup-python@v4
    with:
    python-version: '3.11.x'
  - name: Install Env
    # this should be all we need because shiv will download the deps itself
    run: |
      pip install --upgrade pip
      pip install shiv
      pip install poetry      
  - name: Add CURRENT_TIME env property
    run: echo "CURRENT_TIME_VERSION=v$(date '+%s')" >> $GITHUB_ENV
  - name: Build the sucker
    run: |
      sed -i -e "s/?????/${{ env.CURRENT_TIME_VERSION }}/g" src/__init__.py
      make build      
  - uses: https://github.com/ncipollo/release-action@v1
    with:
    artifacts: "utils"
    body: "It's releasin' time"
    generateReleaseNotes: false
    tag: ${{ env.CURRENT_TIME_VERSION }}
    commit: main
    token: ${{ secrets.PAT }}
